### ISSUE TITLE
Revisions to Sponsorship page

### ISSUE THREAD

**Issue by kariljordan** [carpentries/new-website#241]
Hi! @OscarSiba sent me a Slack message _("When you get a chance, I'd like your input regarding this page on the new website  - do all these benefits for sponsors remain the same?")_. @maneesha asked that I open an issue with answers to those questions regarding our [sponsorship page](https://carp-new-website.netlify.app/support/sponsorship/).

**The "Philanthropy recognition" is definitely no longer a thing, we no longer publish that newsletter. So should "Mention in newsletter" perhaps apply to all sponsorship levels?** 
- [ ] remove philanthropy recognition; keep "mention in newsletter" as is

**Does "Logo on career page" still makes sense/apply?**   
- [ ] Keep logo on careers page (the s is missing on careers). When we relaunch the program we will add logos and if there are no roles at The Carpentries it will say something like "check out open career opportunities with our sponsors."

**And can "Original blog post" apply to all of them?**   
- I don't want original blog post to apply to all of them as that means we could have tons of blog posts from companies. We need to set aside significant benefits for the sponsors who contribute more financially.

**Any other changes you would like made/added to this page?** 

- [ ] Change "Carpentry workshop" to "Carpentries Hosted Workshop"
- [ ] The digital supporter badge appears twice in the table. It should only appear at the top as a benefit to all our sponsors. 
- [ ] Remove the paragraph on newsletter recognition at the bottom as only 4 tiers will receive that. Everyone will receive the digital supporter badge.

**Comment by maneesha** [comment]
@kariljordan and @OscarSiba The points that are checked off have been addressed.

As for your last point, what we have is actually an incomplete list of the details of sponsorship benefits.  You can see on our [current site](https://carpentries.org/sponsorship/) we have the table of sponsor benefits and then below it is a detailed list of what each benefit means.  The list on the new site only includes two of those benefits.  I started to work on including them all but I thought you may want to make some updates first.

* CarpentryCon is listed as a biennial event but we have not been doing it as such
* Social media includes Twitter
* Newsletter is described as biweekly
* Other things I may not be aware of? 

Could we update the page on our current site? I will then use that to update our new site.

**Comment by kariljordan** [comment]
That makes sense. Here is the PR: [#1867](https://github.com/carpentries/carpentries.org/pull/1867)

**Comment by maneesha** [comment]
@OscarSiba  and @kariljordan I have made all the changes we discussed. Please see https://carp-new-website.netlify.app/support/sponsorship/

If this looks good to you, please close this issue.  Otherwise leave any other feedback here.  Thank you!

**Comment by kariljordan** [comment]
@maneesha logo on carpentries.org still shows up in the table and it should be omitted completely.

**Comment by maneesha** [comment]
Thanks.  I have made the change.  See https://carp-new-website.netlify.app/support/sponsorship/

@OscarSiba @kariljordan if this looks good, you can close this issue.

**Comment by maneesha** [comment]
I met with @OscarSiba  to  discuss this.  He says content is all correct and he will review for style changes.

**Comment by maneesha** [comment]
Reviewed with @kariljordan during co-working time today.  All her suggested changes have been implemented via #257.  @OscarSiba Please share any other feedback.  If it all looks good, you can close this issue.

**Comment by OscarSiba** [comment]
- [ ] Please italise "[Carpentries Clippings](https://carp-new-website.netlify.app/newsletter)" under Mention in The Carpentries Newsletter description. 
- [ ] Please add the "Contributor" tick under Mention in The Carpentries Newsletter description. 
- [ ] Please add the "Supporter" tick under Logo on carpentries.org careers page description. 
- [ ] Please remove the "Champion" tick under the Original Blog Post, Themed Community Session, and Attend a Carpentries workshop descriptions. 
- [ ] Under the Themed Community Session description, please hyperlink "virtual Community Session" to our events calendar: https://carp-new-website.netlify.app/community/events/

Thereafter you can close the issue.

**Comment by maneesha** [comment]
Closed with #259
